---
title: "terrine"
author: "Greg Gloor"
date: "`r format(Sys.time(), '%d %B, %Y')`"
geometry: margin=2cm
bibliography: /Users/ggloor/Library/texmf/bibtex/bib/bibdesk_refs.bib
csl: /Users/ggloor/Documents/0_git/csl_styles/frontiers.csl
output:
    pdf_document:
        keep_tex: true
        fig_caption: true
        toc: true
        toc_depth: 2
        includes:
            in_header: /Users/ggloor/Documents/0_git/templates/header.tex
        pandoc_args: [
            "-V", "classoption=twocolumn"
        ]
---

# terrine

**Mike Cyze Sr. made this, or a variant, every Christmas Eve dinner. It was always a highlight!**

Hi Greg!

As requested, here is the recipe that you requested... It is intended for one full and one 3/4 full terrines, oval, each about 9x6 inches, about 3 1/4 tall, with lid on top. I have several and you are free to borrow them. As an aside, do not use a square or rectangular terrine, as the p$\^a$t$\'e$ will not cook well.

The stuffing is made in several stages! It takes about one morning to prepare everything and about 1 1/2 hours to cook.

### Marinate the duck (can use veal or ham if desired and not too fussy)

In a bowl place:

1) Two small skinless magrets sliced into 1/2 inch strips

2) 3 or 4 TB cognac or Armagnac or good brandy

3) Big pinch of salt and pepper

4) Pinch of thyme

5) Pinch of allspice

6) 2 TB finely minced shallots or green onion

Marinate the duck in the bowl with the cognac and seasonings. Set aside.

Before using separate the meat from the marinade. Reserve the marinade.

#### Stuffing:

1) 1/2 cup finely minced cooking onion

2) 2 TB butter (I used rendered duck fat in 2018)

- Note: Cook onion slowly, for about 8 minutes till translucent on low heat.

Scrape into a large mixing bowl....

Pour into mixing bowl.

3) 1 lb ground pork
4) 1 lb ground beef
5) 3/4 lb ground turkey
6) 3 eggs, lightly beaten
7) 2 tsp salt
8) 1/4 tsp black pepper
9) Big pinch of allspice
10) 1/2 tsp thyme

add 1/2 cup port or Madeira — according to your taste, reduced about 40% in skillet

Add all the ingredients to mixing bowl and beat vigorously with a wooden spoon till the mixture has lightened in texture and is thoroughly  blended. This requires arm strength!

Saut$\'e$ a small mouthful to check for salt, pepper, etc. It must be perfectly flavoured!

Set the stuffing aside.

## PUTTING IT ALL TOGETHER

Preheat oven to 350 deg

Two 8 cup oval terrines (as noted above)

Sheets or strips of fresh pork fat back or bellies, pounded or sliced to 1/8 inch thick. skin on if possible to get the collagen

Duck stuffing -above-

Bay leaf below the pork back, I use about 6 per terrine

Sheet of pork fat or strips to cover terrines

* Line terrines with sheets or strips of pork fat, including sides of terrines.

Beat reserved marinade into pork/beef/turkey stuffing (above)

Dip hand in cold water so meat does not stick to hand

Place about 1 to 1 1/2 inch of stuffing onto pork fat

Arrange some duck strips onto stuffing, unevenly

Cover with more stuffing, perhaps 3/4 inch thick, pack down

Arrange more duck strips, not close to edge

Add more stuffing, more or less level with top of terrine

Place bay leaf on top

Cover with sheet or strips of pork fat

Enclose top of terrine with aluminium foil...

Cover with lid.

Repeat for second terrine with left overs.

May be only 3/4 full...

Place the terrines in a pan of boiling water (I use a bottom of roaster)

So that the water comes up about halfway on side of terrines

Add water if it gets too low

Set in lower third of preheated oven and cook for 1 1/2 hours.

The pâté is done when it has shrunk slightly and the juices run clear. Internal temperature of 155 degrees is perfect.

Now the critical part.

Take the terrines out of the water and set them on a board or old towels on a cookie sheet.

Remove lid and place an oval piece of wood on top of terrine. (I have some).

On it place  a 3 to 4 lbs weight so as to pack the terrine and there are no air holes left. (I use a brick or 4 lbs of scuba weights). The clear juices will run onto towels.

Allow to cool at room temperature for a few hours and then chill it overnight.

AND THEN TRY NOT TO EAT TOO MUCH OF IT... (after removing the foil and bay leaf)

Basically this is it.. ! In past years I ground my own meat and even carved fresh duck: that was a waste of time! Grocers carry your requirements!

HAVE FUN!
m
